[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
agent_registry = "72Ap2EvaFejm8B2HA7m4vtwnygH2gUJ4bTqdMgFkauVy"
data_blink = "8JwHGZjAXqD1ZjSLQYq1eqEGnHXiqbTU1yXAEkygwuKo"
delegation = "46znqjLJSWhj1j7By7cycJY5ZhouCJHwgpKoYpmTsBdU"
document_registry = "B9jwdt5kc95CkdTrPEYM4HkFNp4NZNdXjKMLHvDGqTQ7"
human_pay = "9rAuzu9kTkk92VnHHYfYGKJzjqjQnhA7TzKGGDWrX62C"
human_registry = "2QtqddEyVhJWV7ysU1b8mpvQrQpWr84yxiHyqUqRcDzL"
receipts = "62tKD1n3nJkiXtGSDAQbARxrMggfSBK6oq5YVrXzUjXe"

[programs.localnet]
agent_registry = "Co3EAFUnyPLrc13gXkj5wneUkfJFvm16bqB11MGpWUzX"
data_blink = "GYUeSsQfLYrYc5H27XdrssX5WgU4rNfkLGBnsksQcFpX"
delegation = "3m16nfFpUtcCgjFWon3qTuttpTpNu6bnYde5yeXbC1ZF"
document_registry = "FZwCZWpLsn8kL1JAPPNtgrGBw5kaaHsbLyrJ7znVbwVE"
human_pay = "J5GJygKKx6thzLmZ23oEzGmtaDWXji2zHpSDWQdDDH7S"
human_registry = "8A98ekw15Af1k8KW7cdAU7gEHNcE6fn2EznW9N6B62gn"
receipts = "9CWJYBXCAiK7ygWTh8DAhLg8PycWonB7fRGSxWEPYAMp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]
exclude = ["programs/common"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
