[package]
name = "humanrail-common"
version = "0.1.0"
description = "Shared types and interfaces for HumanRail programs"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "humanrail_common"

[features]
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.32.1"
